// generated by tools/blender/render_sprites.py - one line per sprite pack
registerSpritePack("ranger",{"fw": 320, "fh": 400, "v": 1790533097, "anims": {"idle": {"n": 8, "file": "sprites/ranger/idle.png"}, "walk": {"n": 16, "file": "sprites/ranger/walk.png"}, "attack": {"n": 12, "file": "sprites/ranger/attack.png"}}});
