"""
Build every catalog item whose image is in images/items/, then write data/items.js for the game.

  python tools/build_items.py              # build new images only, then refresh data/items.js
  python tools/build_items.py --force iron_helmet,katana     # rebuild these even if already built
  python tools/build_items.py --data-only  # only refresh data/items.js

Source of truth: tools/item_catalog.csv (see docs/item_standard.md).
"""
import argparse, csv, glob, json, os, re, subprocess, sys
sys_stdout_utf8 = __import__("sys").stdout.reconfigure(encoding="utf-8", errors="replace")   # Thai names on a cp1252 console

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
ap = argparse.ArgumentParser()
ap.add_argument("--force", default="")
ap.add_argument("--data-only", action="store_true")
ap.add_argument("--refit", default="", help="ids to re-attach and re-render with the catalog fit_* values (model is kept)")
a = ap.parse_args()
force = set(filter(None, a.force.split(",")))
rows = list(csv.DictReader(open(os.path.join(ROOT, "tools", "item_catalog.csv"), encoding="utf-8-sig")))
bases = sorted(os.path.basename(p)[5:] for p in glob.glob(os.path.join(ROOT, "sprites", "hair_*")))
def image_of(r):   # images/items/<id>.png / .jpg / .jpeg / .webp
    for ext in (".png", ".jpg", ".jpeg", ".webp"):
        f = os.path.join(ROOT, "images", "items", r["id"] + ext)
        if os.path.exists(f): return f
    return None
built = lambda iid: bases and all(os.path.exists(os.path.join(ROOT, "sprites", f"item_{iid}_{b}", "idle.png")) for b in bases)

def fit_args(r):   # per-item fit from the catalog (empty = defaults)
    out = ["--grip", r["grip"]] if r.get("grip") else []
    for k in ("size", "sink", "rot", "offset"):
        if r.get("fit_" + k): out += ["--" + k, r["fit_" + k]]
    return out
for iid in filter(None, a.refit.split(",")):
    r = next(x for x in rows if x["id"] == iid)
    print(f"=== refit {iid} {fit_args(r)}", flush=True)
    subprocess.run([sys.executable, "tools/item_layers.py", "--id", iid, "--slot", r["slot"], "--image", image_of(r) or "", "--from", "attach"] + fit_args(r), cwd=ROOT)
if a.refit: a.data_only = True
if not a.data_only:
    todo = [r for r in rows if image_of(r) and (r["id"] in force or not built(r["id"]))]
    print(f"{len(todo)} item(s) to build for bases {', '.join(bases)}")
    for i, r in enumerate(todo, 1):
        print(f"=== [{i}/{len(todo)}] {r['id']} ({r['name_th']}, {r['slot']})", flush=True)
        cmd = [sys.executable, "tools/item_layers.py", "--id", r["id"], "--slot", r["slot"], "--image", image_of(r)] + fit_args(r)
        if subprocess.run(cmd, cwd=ROOT).returncode != 0:
            print(f"!!! {r['id']} failed - skipped, continuing")

# ---------- data/items.js ----------
STAT = {"ATK": "atk", "MATK": "atk", "DEF": "def", "MDEF": "mdef", "LUK": "luk"}
ICO = {"head": "🎩", "hand_r": "⚔️", "hand_l": "🏹", "arm_l": "🛡️", "back": "🧣"}
RAR = {"starter": "", "common": "", "rare": "rare", "epic": "epic", "legend": "epic", "fashion": "fash"}
TIER_TH = {"starter": "เริ่มต้น", "common": "ธรรมดา", "rare": "หายาก", "epic": "มหากาพย์", "legend": "ตำนาน", "fashion": "แฟชั่น"}
CLS_TH = {"knight": "นักดาบ", "ranger": "นักธนู", "witch": "จอมเวท", "novice": "โนวิซ"}
out = []
for r in rows:
    ok = built(r["id"])
    if not ok and not r["in_game"]:
        continue  # not built yet: not in the game
    e = {"key": r["game_key"], "id": r["id"], "merge": bool(r["in_game"])}
    if ok:
        e["layer"] = r["id"]
        if os.path.exists(os.path.join(ROOT, "assets", "icons", r["id"] + ".png")): e["icon"] = f"assets/icons/{r['id']}.png"
    if r["class_only"]: e["classes"] = [r["class_only"]]
    if not r["in_game"]:
        e.update(ico=ICO[r["slot"]], eq=r["game_slot"], price=int(r["price"]), rar=RAR[r["tier"]])
        for k, v in re.findall(r"\b([A-Z]+) \+(\d+)(?!%)", r["stats"]):
            if k in STAT: e[STAT[k]] = e.get(STAT[k], 0) + int(v)
        lock = f" · ใส่ได้เฉพาะ{CLS_TH[r['class_only']]}" if r["class_only"] else ""
        e["desc"] = f"{TIER_TH[r['tier']]} · {r['stats']}{lock}"
    out.append(e)
os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
with open(os.path.join(ROOT, "data", "items.js"), "w", encoding="utf8") as f:
    f.write("// generated by tools/build_items.py from tools/item_catalog.csv - do not edit by hand\n")
    for e in out:
        f.write("registerItem(" + json.dumps(e, ensure_ascii=False) + ");\n")
print(f"data/items.js: {len(out)} items ({sum(1 for e in out if 'layer' in e)} with 3D layers)")
